In [1]:
import numpy as np

In [2]:
# Estadística
arreglo = np.array([[23,24,25],
                 [10,11,12]])
print("Promedio total con np.mean():")
print(np.mean(arreglo))   # promedio de todos los elementos

Promedio total con np.mean():
17.5


In [3]:
print("Promedio por columnas (axis=0):")
print(np.mean(arreglo, axis=0))   # promedio por columna

Promedio por columnas (axis=0):
[16.5 17.5 18.5]


In [4]:
print("Promedio por filas (axis=1):")
print(np.mean(arreglo, axis=1))   # promedio por fila

Promedio por filas (axis=1):
[24. 11.]


In [5]:
print("Desviación estándar total con np.std():")
print(np.std(arreglo))
print()
print("Desviación estándar por columnas (axis=0):")
print(np.std(arreglo, axis=0))

Desviación estándar total con np.std():
6.551081335677848

Desviación estándar por columnas (axis=0):
[6.5 6.5 6.5]


In [6]:
print("Suma total con np.sum():")
print(np.sum(arreglo))
print()

print("Suma por columnas (axis=0):")
print(np.sum(arreglo, axis=0))
print()

print("Suma por filas (axis=1):")
print(np.sum(arreglo, axis=1))
print()

Suma total con np.sum():
105

Suma por columnas (axis=0):
[33 35 37]

Suma por filas (axis=1):
[72 33]



In [7]:
# Secuencias
print("Ejemplo de np.arange(inicio, fin, paso):")
arr1 = np.arange(0, 10, 2)   # desde 0 hasta <10, de 2 en 2
print(arr1)
print()

print("Otro ejemplo con np.arange(inicio, fin):")
arr2 = np.arange(5, 15)   # desde 5 hasta <15, de 1 en 1 (por defecto)
print(arr2)
print()

Ejemplo de np.arange(inicio, fin, paso):
[0 2 4 6 8]

Otro ejemplo con np.arange(inicio, fin):
[ 5  6  7  8  9 10 11 12 13 14]



In [8]:
print("Ejemplo de np.linspace(inicio, fin, num):")
lin1 = np.linspace(0, 1, 5)   # 5 puntos entre 0 y 1
print(lin1)
print()

print("Otro ejemplo de np.linspace con endpoint=False:")
lin2 = np.linspace(0, 10, 4, endpoint=False)  # excluye el 10
print(lin2)
print()

Ejemplo de np.linspace(inicio, fin, num):
[0.   0.25 0.5  0.75 1.  ]

Otro ejemplo de np.linspace con endpoint=False:
[0.  2.5 5.  7.5]



In [9]:
# grupos aleatorios
print("Fijamos la semilla para reproducibilidad (seed=42):")
np.random.seed(42)

Fijamos la semilla para reproducibilidad (seed=42):


In [10]:
print("\nEjemplo de np.random.rand(2, 3):")
rand_uniforme = np.random.rand(2, 3)   # distribución uniforme [0,1)
print(rand_uniforme)


Ejemplo de np.random.rand(2, 3):
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]


In [11]:
print("\nEjemplo de np.random.randn(2, 3):")
rand_normal = np.random.randn(2, 3)   # distribución normal (media=0, var=1)
print(rand_normal)


Ejemplo de np.random.randn(2, 3):
[[ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]]


In [12]:
print("\nEjemplo de np.random.randint(0, 10, size=(2, 3)):")
rand_enteros = np.random.randint(0, 10, size=(2, 3))   # enteros entre 0 y 9
print(rand_enteros)


Ejemplo de np.random.randint(0, 10, size=(2, 3)):
[[9 5 8]
 [0 9 2]]


In [13]:
# Algebra Lineal
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])
print("Producto escalar / matricial con np.dot(A, B):")
print(np.dot(A, B))

Producto escalar / matricial con np.dot(A, B):
[[19 22]
 [43 50]]


In [14]:
print("Multiplicación matricial con np.matmul(A, B) o A @ B:")
print(np.matmul(A, B))
print(A @ B)   # forma abreviada

Multiplicación matricial con np.matmul(A, B) o A @ B:
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [15]:
print("Determinante de A con np.linalg.det(A):")
print(np.linalg.det(A))

Determinante de A con np.linalg.det(A):
-2.0000000000000004


In [16]:
print("Matriz inversa de A con np.linalg.inv(A):")
print(np.linalg.inv(A))

Matriz inversa de A con np.linalg.inv(A):
[[-2.   1. ]
 [ 1.5 -0.5]]


In [17]:
print("Autovalores y autovectores de A con np.linalg.eig(A):")
vals, vecs = np.linalg.eig(A)
print("Autovalores:", vals)
print("Autovectores:\n", vecs)

Autovalores y autovectores de A con np.linalg.eig(A):
Autovalores: [-0.37228132  5.37228132]
Autovectores:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [18]:
print("Resolver sistema de ecuaciones Ax = b con np.linalg.solve(A, b):")
b = np.array([1, 2])
x = np.linalg.solve(A, b)
print("Solución x:", x)

Resolver sistema de ecuaciones Ax = b con np.linalg.solve(A, b):
Solución x: [0.  0.5]
