In [1]:
import numpy as np
from pprint import pprint

In [2]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [6]:
a = [1,2,3,4,5.7]
a_array = np.array(a)
a_array

array([1. , 2. , 3. , 4. , 5.7])

In [13]:
array2 = np.zeros((2,2)) # el primer argumento es el shape del array
print("dimensiones: ", array2.ndim, "\n")
print("tipo de array: ", array2.dtype)
array2

dimensiones:  2 

tipo de array:  float64


array([[0., 0.],
       [0., 0.]])

In [16]:
array2 = np.ones((3,2)) # el primer argumento es el shape del array
print("dimensiones: ", array2.ndim, "\n")
print("tipo de array: ", array2.dtype)
array2

dimensiones:  2 

tipo de array:  float64


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
array2 = np.array([1,2,3,4,5,6])
array_transformado = array2.reshape((3,2)) 
# hay que tener en cuenta que el shape tiene que coicidir 
# con la cantidad (length) del array. 2*3 = 6
array_transformado

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
array2 = np.array([1,7,44,46,78,95])
array_transformado = array2.reshape((2,-1)) # el -1 permite autocalcular la dimensión
array_transformado

array([[ 1,  7, 44],
       [46, 78, 95]])

In [14]:
array1 = np.array([[1,2],
                  [3,4]])
array2 = np.array([[5,6],
                  [7,8]])

array_concat = np.concatenate((array1,array2), axis=0)
# el argumento axis permite decidir si cocatenar las filas (0) o columnas (1)
pprint(array_concat)

array_concat1 = np.concatenate((array1,array2), axis=1)
pprint(array_concat1)


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])
array([[1, 2, 5, 6],
       [3, 4, 7, 8]])


In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

pprint(np.vstack((a, b)))

array([[1, 2, 3],
       [4, 5, 6]])


In [5]:
a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 6]])

pprint(np.hstack((a, b)))

array([[1, 2, 3, 4, 5, 6]])


In [7]:
arr = np.array([0, 1, 2, 3, 4, 5])

pprint(np.split(arr, 3))   # divide en 3 partes iguales

[array([0, 1]), array([2, 3]), array([4, 5])]


In [9]:
arr2D = np.array([[1, 2, 3],
                  [4, 5, 6]])

ravel_arr = arr2D.ravel()
pprint(ravel_arr)
# Modifico el resultado para mostrar que afecta al original
ravel_arr[0] = 99
pprint(arr2D)

array([1, 2, 3, 4, 5, 6])
array([[99,  2,  3],
       [ 4,  5,  6]])


In [10]:
arr2D = np.array([[1, 2, 3],
                  [4, 5, 6]])

flatten_arr = arr2D.flatten()
print(flatten_arr)

# Modifico el resultado para mostrar que NO afecta al original
flatten_arr[0] = 99
print(arr2D)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = a + b
c

array([5, 7, 9])

In [4]:
c = a - b
c

array([-3, -3, -3])

In [6]:
c = a * b
c

array([ 4, 10, 18])

In [7]:
c = a / b
c

array([0.25, 0.4 , 0.5 ])

In [8]:
c = a ** b
c

array([  1,  32, 729])